name: dog
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.5
  multi_select_flutter: ^4.1.3
  firebase_database: ^11.3.4
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - IMG/
    - IMG/acana2.png